### PR TITLE
Update to `@nextcloud/vue@8`

### PR DESCRIPTION
**Pull request by ShGKme**
### 🖼️ Screenshots

image

### 🚧 Tasks

- [x] Update `@nextcloud/vue`
- [x] Update global server styles
- [x] Adjust some components: add required aria-label to button and use new NcTextArea

### CODE REVIEW

**Review by Antreesy — APPROVED** [review]
:palm: :seal:

**Review by DorraJaouad — APPROVED** [review]
:)

**Comment by nickvergessen** [comment]
Lint has some issues:
```
/home/runner/work/talk-desktop/talk-desktop/src/authentication/renderer/AuthenticationApp.vue
Error:   74:22  error  Missing file extension "mjs" for "@nextcloud/vue/dist/Components/NcButton.js"       import/extensions
Error:   75:27  error  Missing file extension "mjs" for "@nextcloud/vue/dist/Components/NcLoadingIcon.js"  import/extensions
Error:   76:25  error  Missing file extension "mjs" for "@nextcloud/vue/dist/Components/NcTextField.js"    import/extensions
```

Saw them in other apps too. and there are only mjs and cjs files in the dist folder, no more js

**Comment by Antreesy** [comment]
> Saw them in other apps too.


Also saw when migrated in spreed repo, but it's gone after rebase
Might have been fixed by
"@nextcloud/eslint-config": "^8.3.0"

**Pull request merged**
