### PR TITLE
fix(mac): show window on activate when minimized to tray

### PR DESCRIPTION
**Pull request by ShGKme**
### ☑️ Resolves

* Fix: https://github.com/nextcloud/talk-desktop/issues/885
* Similar to https://github.com/nextcloud/talk-desktop/pull/852
  * That PR only fixed it for closed windows like the login window
  * This PR also fixes it when the window is not closed but minimized to the system tray

---

Additional changes after discussions are forked to https://github.com/nextcloud/talk-desktop/pull/911

### CODE REVIEW

**Comment by i2h3** [comment]
> Only do that with the main Talk window. Close login window = quit the app

This one. I am used to that behavior from many apps. There is no point in keeping it running in the background when you are not signed in. With its own apps, Apple is more and more quitting apps entirely on their last window close, too. Obviously that is inappropriate for a chat app.

But I would not consider it to be _that_ important difference.

**Review by i2h3 — APPROVED** [review]

**Comment by ShGKme** [comment]
@Ivansss Despite our discussion yesterday but having @i2h3's comment and @SystemKeeper reaction, I went this way.
- Talk window - reopen on the Dock icon click (never closed, lives in the system tray)
- Login/Welcome windows - quit app on window close

Is it fine, or you'd insist on reopen for the login window dock icon click?

**Comment by ShGKme** [comment]
Actually, after a new discussion with designers, I'm not sure we should close the login window 😣

I'll separate this PR into 2 parts:
- Fixing reopening the Talk window
- Quitting from the login window

**Comment by ShGKme** [comment]
PR is updated:
- This PR only fixes the issue
- The new behavior is moved to https://github.com/nextcloud/talk-desktop/pull/911

**Review by Antreesy — COMMENTED** [review]
LGTM

**Pull request merged**
