### PR TITLE
Add release scripts

### PR DESCRIPTION
**Pull request by ShGKme**
### 🖼️ Screenshots

build

_(Steps count are incorrect on the gif, fixed)_

### 🚧 Tasks

- [x] Add script to make a release packages
  - Check that there are no uncommitted changes
  - Clone Talk if needed to `speed`, checkout tag
  - Install all dependencies
  - Package
- [x] Add instructions to `README.md`

### CODE REVIEW

**Comment by ShGKme** [comment]
> only builds the arm64 version, but I guess that's expected on a arm64 processor

Yess. And now you can build an ARM package each release with one command 😀

**Review by SystemKeeper — APPROVED** [review]
👍

**Review by Antreesy — APPROVED** [review]
Works on Linux
It took some time to clone 'spreed" (have it externally), but i guess, it's cleaner and better for production release purposes, rather then external setup

**Comment by ShGKme** [comment]
A bit not correct for already cloned Talk to `./spreed/`, there is no `fetch/pull`

**Comment by ShGKme** [comment]
> It took some time to clone 'spreed" (have it externally), but i guess, it's cleaner and better for production release purposes, rather then external setup

Cloned repo is not removed, so it will be faster next time.

But at this moment I thought about it if this should be configurable to use talk from your `TALK_PATH` or to use some temp directory...

**Comment by SystemKeeper** [comment]
If you always clone it would make sense to specify `—depth=1` to not clone everything every time

**Comment by ShGKme** [comment]
Updates:
1. Cloning a shallow repo with `--depth=1` only specified tag
2. If is was already cloned - fetch before checkout (also shallow version)
3. Clone to a temp directory so no working tree is touched

**Review by SystemKeeper — APPROVED** [review]
Tested and works nicely with the temp directory :-)

**Comment by ShGKme** [comment]
Arr, there is no check for fixup commits on CI in this repo ><

**Pull request merged**
