### PR TITLE
feat: add play sound config

### PR DESCRIPTION
**Pull request by ShGKme**
### ☑️ Resolves

* Fix: https://github.com/nextcloud/talk-desktop/issues/630

Desktop alternative for the following web settings (but with respect DND option):

image

For simple testing - check initial state

image

### 🖼️ Screenshots

image

### CODE REVIEW

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/spreed/issues/13437 🙈

**Comment by ShGKme** [comment]
> Ref https://github.com/nextcloud/spreed/issues/13437 🙈

Wrong link? Or how is lobby related?

**Comment by nickvergessen** [comment]
Check the description

**Review by DorraJaouad — APPROVED** [review]
Tested

**Comment by ShGKme** [comment]
Still fighting ESLint. I don't understand the error

**Review by Antreesy — APPROVED** [review]
Tested. init.js had unused imports after you moved user status listener

**Comment by ShGKme** [comment]
Rebased onto main after a long time. No changes. @Antreesy's changes are included.

**Comment by ShGKme** [comment]
> Still fighting ESLint. I don't understand the error

The error still exists but doesn't lead to fail eslint check...

**Comment by ShGKme** [comment]
> Check the description

For clarification: that link is not related. This PR is only about call/notifications sound, same as available on the Web. Not about disabling any sounds completely.

**Pull request merged**
