### PR TITLE
build: add macOS dmg distributive

### PR DESCRIPTION
**Pull request by ShGKme**
### ☑️ Resolves

* Fix: https://github.com/nextcloud/talk-desktop/issues/843

Make `.dmg` distributive:
- Simple to use for end-users, just drag and drop
- No admin right required
- Alternative - `.pkg`, a classic installer

### 🖼️ Screenshots

image

image

image

### CODE REVIEW

**Review by Antreesy — APPROVED** [review]
LGTM

**Comment by ShGKme** [comment]
Checked category from Social Networking to Business aligned with category change for Nextcloud Talk mobile client on iOS

**Comment by ShGKme** [comment]
Changed bundleId from `com.nextcloud.NextcloudTalk` to `com.nextcloud.talk.mac` following Talk iOS.

**Comment by ShGKme** [comment]
Considering 👍 as approve. Rebased, squashed, merging.

**Pull request merged**
